Initial app setup
kickdrum/kd-ref-code-web-app pull request #2
Opened 2021-02-18 07:44 UTC by Prateek-Kickdrum

Added ReadMe for all the functionality.
Setting up Sonarqube
Setting up Sentry
Initial code structure
Internationalization

2021-02-18 07:59 UTC, FarhatRV requested changes

2021-02-18 07:59 UTC, FarhatRV commented on .env.prod
> +REACT_APP_SENTRY_DSN = ""
let us not make configs where developer has to commit API keys or any sensitive passwords/passcodes into the code repos.

2021-02-18 07:59 UTC, FarhatRV commented on .env.dev
> +GENERATE_SOURCEMAP=false
we should generate sourcemap in dev for debugging ease.

2021-02-18 07:59 UTC, FarhatRV commented on .env.prod
> +REACT_APP_API_KEY = ""
same as above

2021-02-18 07:59 UTC, FarhatRV commented on .env.prod
> +REACT_APP_SENTRY_DSN = ""
they should be passed from env variables passed from build scripts/build provider - eg, Codebuild's environment variables.

2021-02-18 07:59 UTC, FarhatRV commented on public/index.html
> +  <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
add a README comment here to help developer easily change favicons in their apps

2021-02-18 07:59 UTC, FarhatRV commented on sonar-project.js
> +      "sonar.projectName": process.env.REACT_PROJECT_NAME,
add README comments here expalining each field

2021-02-18 07:59 UTC, FarhatRV commented on src/index.js
> +reportWebVitals();
keep it as a plug and play thing rather than a mandate - like a Boolean env variable saying whether it should be enabled or not - we don't wanna report these for each env generally.

2021-02-18 07:59 UTC, FarhatRV commented on src/index.js
> +reportWebVitals();
just like `REACT_APP_ENABLE_SENTRY`

2021-02-18 07:59 UTC, FarhatRV commented on src/index.scss
> +// @import "./scss/common/reset.scss";
why is it commented, remove if not needed or exaplin via a comment

2021-02-18 07:59 UTC, FarhatRV commented on src/reportWebVitals.js
> +      getCLS(onPerfEntry);
please use fullforms instead of CLS, FCP, etc

2021-02-18 07:59 UTC, FarhatRV commented on src/scss/common/reset.scss
> +/* http://meyerweb.com/eric/tools/css/reset/
explain with a comment what is reset.css and why is it needed

2021-02-18 07:59 UTC, FarhatRV commented on src/scss/common/typography.scss
> +  // color: $link-color;
remove commented code

2021-02-18 07:59 UTC, FarhatRV commented on src/utils/axiosInterceptor.js
> +axios.defaults.timeout = 1 * 300 * 1000; //
complete the comment - better if we keep this value configurable for diff env

2021-02-18 07:59 UTC, FarhatRV commented on src/utils/axiosInterceptor.js
> +
not too sure if we need this specifically AWS cognito targetted axios interceptor for a generic app - please explain why is it needed and the use cases covered in this file as a comment

2021-02-18 08:00 UTC, FarhatRV commented
resolve merge commits

2021-02-18 09:20 UTC, Prateek-Kickdrum commented on .env.prod
> +REACT_APP_SENTRY_DSN = ""
These will be the variables that will be used in the code. 
Users have to set the value of these variables in the script or from the secret manager. They will not be present in the code.
The following files are for two purposes, 
1. TO run the app using a specific env.
2. To specify the variables which are going to be used in the code.

2021-02-18 09:25 UTC, Prateek-Kickdrum commented on sonar-project.js
> +      "sonar.projectName": process.env.REACT_PROJECT_NAME,
We can provide a reference link in the doc which will tell everything about the properties and sonarqube.
We are just giving the solution code.

2021-02-18 09:27 UTC, Prateek-Kickdrum commented on src/reportWebVitals.js
> +      getCLS(onPerfEntry);
This is all auto-generated code from Create-react-app.

2021-02-18 15:42 UTC, FarhatRV commented on .env.prod
> +REACT_APP_SENTRY_DSN = ""
lets have comments in code wherever they are used with examples of how these keys can look

2021-02-19 10:50 UTC, Prateek-Kickdrum commented on .env.dev
> +GENERATE_SOURCEMAP=false
done

2021-02-19 11:04 UTC, Prateek-Kickdrum commented on src/scss/common/reset.scss
> +/* http://meyerweb.com/eric/tools/css/reset/
done

2021-02-19 11:06 UTC, Prateek-Kickdrum commented on src/scss/common/typography.scss
> +  // color: $link-color;
done

2021-02-19 11:07 UTC, Prateek-Kickdrum commented on src/utils/axiosInterceptor.js
> +axios.defaults.timeout = 1 * 300 * 1000; //
done

2021-02-19 11:08 UTC, Prateek-Kickdrum commented on src/utils/axiosInterceptor.js
> +
Removed it as Login feature will be done as part of other PR

2021-02-19 11:34 UTC, FarhatRV requested changes

2021-02-19 11:34 UTC, FarhatRV commented on .env.prod
> +GENERATE_SOURCEMAP=true
please disable sourcemap for prod

2021-02-19 11:34 UTC, FarhatRV commented on README.md
> +# KD Ref App for mobile development
please update the title to web app

2021-02-19 11:34 UTC, FarhatRV commented on sonar-project.js
> +      "sonar.projectName": process.env.REACT_PROJECT_NAME,
please link the reference link here too

2021-02-19 11:34 UTC, FarhatRV commented on src/components/common/sentry-error-boundary/SentryErrorBoundary.js
> +      What is it
can we remove this `What is it` text?

2021-02-19 11:34 UTC, FarhatRV commented on src/constants/constants.js
> +export default {};
thanks for adding these placeholders for constants

2021-02-19 11:34 UTC, FarhatRV commented on src/index.js
> +if (isWebVitalsEnabled) {
thanks for including web vitals reporting

2021-02-19 11:34 UTC, FarhatRV commented on src/setupTests.js
> +// jest-dom adds custom jest matchers for asserting on DOM nodes.
is this file needed? it just has an import!

2021-02-19 11:34 UTC, FarhatRV commented on src/utils/axiosInterceptor.js
> +  return !!err.isAxiosError && !err.response;
can we remove the double not `!!`

2021-02-19 11:34 UTC, FarhatRV commented on src/components/App.scss
> +  // text-align: center;
remove commented code

2021-02-19 11:36 UTC, Prateek-Kickdrum commented on README.md
> +# KD Ref App for mobile development
Copy Paste :-D

2021-02-19 11:42 UTC, Prateek-Kickdrum commented on src/setupTests.js
> +// jest-dom adds custom jest matchers for asserting on DOM nodes.
Yes without it testing app does not work. Its a system generated file which is used by react framework for initializing testing lib jest dom

2021-02-19 11:46 UTC, FarhatRV approved these changes

2021-02-19 13:59 UTC, merged